// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQPY3NdSX0_TUGBv1ibh-I7LzmEVokiIY',
    appId: '1:311495889181:web:a6239c618f675199f911f4',
    messagingSenderId: '311495889181',
    projectId: 'horarios-bee02',
    authDomain: 'horarios-bee02.firebaseapp.com',
    storageBucket: 'horarios-bee02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN5DJ_iuvktqv8-tQlU74Ava5o09DSRjg',
    appId: '1:311495889181:android:647e5e331a5e74f1f911f4',
    messagingSenderId: '311495889181',
    projectId: 'horarios-bee02',
    storageBucket: 'horarios-bee02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmxG56c6TETECY9cYpioL0SZoVNJmvuIU',
    appId: '1:311495889181:ios:955c5f76cefe16a0f911f4',
    messagingSenderId: '311495889181',
    projectId: 'horarios-bee02',
    storageBucket: 'horarios-bee02.appspot.com',
    iosBundleId: 'com.example.horarios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmxG56c6TETECY9cYpioL0SZoVNJmvuIU',
    appId: '1:311495889181:ios:c7e62aedfd04ff2ff911f4',
    messagingSenderId: '311495889181',
    projectId: 'horarios-bee02',
    storageBucket: 'horarios-bee02.appspot.com',
    iosBundleId: 'com.example.horarios.RunnerTests',
  );
}
